#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := ../RGBMatrix/RGBMatrix.cpp ../RGBMatrix/Line.cpp ../RGBMatrix/Circle.cpp ../RGBMatrix/Rectangle.cpp

# header files in this project
HEADERS := hwlib.hpp ../RGBMatrix/RGBMatrix.h ../RGBMatrix/Drawable.h ../RGBMatrix/Line.h ../RGBMatrix/Circle.h ../RGBMatrix/Rectangle.h

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
